common: &common
  adapter:  postgresql
  host: 192.168.1.16
  pool:     5
  timeout:  5000
  min_messages: warning

development: &development
  <<: *common
  database: forwindlocal
  username: harry
  password: caul


test: &test
  <<: *common
  database: forwind_test

production: &production
  <<: *common
  database: forwind_development