# BlogKit configuration file
---
# ================ Visual settings ================

blog_name: 'Forwind Updates'

# Show "Published By ..."
show_user_who_published: true

post_date_format: '%B %e %Y' # strftime format

# Enable gravatar support next to comments and posts
gravatar: false

# Allow people who are not logged in to post anonymous comments
anonymous_comments: false

# User Markdown for parsing posts
use_markdown: true

# Only enabled if you don't use markdown
# html_editor: true

layout: 'home'
admin_layout: 'default'

theme: 'mac_classic'

# Link to the default user path (/users/[id])
link_to_user: true

# Show line numbers next to code
show_link_numbers: false

# Akismet settings (spam filtering)
# akismet_key: '__your_key_here__'

# Blog URL - required for akismet
blog_url: 'http://www.forwind.net/blog_posts'

# Image Uploading options - assume paperclip is installed
#paperclip:
  # path: ':rails_root/public/system/:attachment/:id/:style/:filename'
  
  # # S3 support
  # :storage: :s3
  # :s3_credentials: "config/s3.yml"
  # :path: ":attachment/:id/:style.:extension"
  
  
  # You can also override the image sizes for paperclip

